/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'on-background': '#251915',
        'on-primary-fixed-variant': '#8a1c01',
        'on-tertiary': '#ffffff',
        primary: '#881b00',
        'inverse-on-surface': '#ffede9',
        'secondary-container': '#e2dfdf',
        'tertiary-fixed': '#e4e2de',
        'surface-container-highest': '#f6ddd8',
        'surface-container': '#efeded',
        'on-secondary-container': '#636262',
        'inverse-primary': '#ffb4a3',
        'outline-variant': '#e0bfb8',
        'primary-fixed': '#ffdad2',
        'surface-container-high': '#fbe3dd',
        background: '#fff8f6',
        'on-surface': '#251915',
        'on-primary-fixed': '#3d0700',
        'on-primary-container': '#ffcbbf',
        'surface-tint': '#ac3417',
        'on-surface-variant': '#59413c',
        outline: '#8c716a',
        'primary-container': '#aa3316',
        secondary: '#5f5e5e',
        'surface-dim': '#edd5cf',
        'on-error': '#ffffff',
        'surface-container-low': '#fff0ed',
        'surface-bright': '#fff8f6',
        'inverse-surface': '#3c2d2a',
        'secondary-fixed': '#e5e2e1',
        'on-secondary': '#ffffff',
        tertiary: '#454643',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'surface-variant': '#f6ddd8',
        'on-primary': '#ffffff',
        'tertiary-container': '#5d5d5a',
        'on-error-container': '#93000a',
        'on-tertiary-container': '#d8d6d2',
        'primary-fixed-dim': '#ffb4a3',
        surface: '#fbf9f8',
        'surface-container-lowest': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        base: '8px',
        sm: '12px',
        md: '24px',
        gutter: '24px',
        lg: '48px',
        xl: '80px',
        'container-max': '1200px',
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'sans-serif'],
        serif: ['"Source Serif 4"', 'serif'],
      },
      fontSize: {
        caption: ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'title-lg': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
      },
      maxWidth: {
        'container-max': '1200px',
      },
    },
  },
  plugins: [],
};
