spring:
  application:
    name: subscription-service
  datasource:
    url: jdbc:postgresql://postgres:5432/asanrezerv
    name: asanrezerv
    password: asanrezerv
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    producer:
      bootstrap-servers: kafka:9092