spring:
  application:
    name: restaurant-service
  datasource:
    url: jdbc:postgresql://postgres:5432/asanrezerv
    name: asanrezerv
    password: asanrezerv
  jpa:
    hibernate:
      ddl-auto: update
  services:
    subscription-service:
      url: http://subscription-service:8080
    media-service:
      url: http://media-service:8080
    auth-service:
      url: http://auth-service:8080

  kafka:
    producer:
      bootstrap-servers: kafka:9092