spring:
  application:
    name: staff-service
  datasource:
    url: jdbc:postgresql://postgres:5432/rezervet
    name: rezervet
    password: rezervet
  jpa:
    hibernate:
      ddl-auto: update
  auth-service:
    url: http://auth-service:8080
  restaurant-service:
    url: http://restaurant-service:8080

feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false