spring:
  application:
    name: subscription-service
  datasource:
    url: jdbc:postgresql://postgres:5432/asanrezerv
    name: asanrezerv
    password: asanrezerv
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    producer:
      bootstrap-servers: kafka:9092
  client:
    urls:
      restaurant-service: http://restaurant-service:8080
      auth-service: http://auth-service:8080
      reservation-service: http://reservation-service:8080